version: "3"  # optional since v1.27.0
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./configs/${PORTAINER_EDGE_ID}.conf1:/conf1
      - ./configs/${PORTAINER_EDGE_ID}.conf2:/conf2
    
